[project]
authors = ["JafarAbdi <jafar.uruc@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "cpp_playground"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
# ninja = ">=1.12.1,<2"
# cmake = ">=3.30.5,<4"
cpp-expected = ">=0.1.0,<2"
spdlog = ">=0.14.1,<2"
fmt = ">=10.0.2,<12"
range-v3 = ">=0.12.0,<0.13"
